# Whether not the game will be active on server start
active: true

# Determines whether hearts should be shown as hardcore-style or regular-style
hardcoreStyle: true

# If true, players in spectator mode will not be able to send messages to chat. Operators bypass this.
blockSpectatorChat: true

# Amount of time in seconds players will be considered as "attacking" after attempting to kill someone
attackDuration: 30

# String an item should be renamed to in order to activate Forgery ability
forgeItemName: "Forgery"

# ID of item that should be sacrificed to trigger reanimation
reanimateSacrifice: "TOTEM_OF_UNDYING"

# Focus time in seconds required to target someone with a spyglass
spyglassTargetTime: 10.0
# Magic number that modifies spyglass sensitivity. Larger is more sensitive.
spyglassSensitivity: 0.1

# Effective range of Peripherals ability
peripheralsRange: 10

# Doctor Rescue ability range
rescueRange: 8.0

# Cost (in levels) to trigger Scatter
scatterCost: 5
# Cost (in levels) to trigger Toadify
toadifyCost: 15
# Cost (in levels) to trigger Fog of War
fogOfWarCost: 10
# Effective range of Fog of War
fogOfWarRange: 30
# Cost (in levels) to trigger Vanish
vanishCost: 10
