# Whether not the game will be active on server start
active: false

# Determines whether hearts should be shown as hardcore-style or regular-style
hardcoreStyle: true

# If true, players in spectator mode will not be able to send messages to chat. Operators bypass this.
blockSpectatorChat: true

# If true, spectating players will appear to leave the game when they die and will be hidden from the tab list when online.
# Remember to set the game rule to hide player death messages if true!
hideDeadPlayers: false

# Amount of time in seconds players will be considered as "attacking" after attempting to kill someone
attackDuration: 30

# String an item should be renamed to in order to activate Forgery ability
forgeItemName: "forgery"

# ID of item that should be sacrificed to trigger reanimation
reanimateSacrifice: "TOTEM_OF_UNDYING"

# Focus time in seconds required to target someone with a spyglass
spyglassTargetTime: 10.0
# Magic number that modifies spyglass sensitivity. Larger is more sensitive.
spyglassSensitivity: 0.1

# Effective range of Peripherals ability
peripheralsRange: 20

# Doctor Rescue ability range
rescueRange: 8.0

# Cost (in levels) to trigger Scatter
scatterCost: 4
# Cost (in levels) to trigger Toadify
toadifyCost: 4
# Cost (in levels) to trigger Fog of War
fogOfWarCost: 8
# Effective range of Fog of War
fogOfWarRange: 30
# Cost (in levels) to trigger Vanish
vanishCost: 8

# Number of targets hunters will be given
hunterNumTargets: 3

# Roles that you want to ensure at least one of exists in the game.
# If the role is unique, it will only be added once. If it is not, it could be added multiple times.
# If there are not enough players in the game, the randomization command will fail.
requiredRoles:
  - "GODFATHER"
  - "MAFIOSO"
  - "REANIMATOR"
  - "INVESTIGATOR"
  - "APOTHECARY"
  - "PRIEST"
  - "SERIAL_KILLER"
  - "HUNTER"

# Roles that will not be assigned to players. Overridden by requiredRoles.
# If there is some issue that makes the game impossible to set up, the randomization command will fail.
bannedRoles:

# Minimum required ratios for certain types of roles.
# If these add up to more than 1.0 the randomization command will fail.
roleRatio:
  mafia: 0.15
  village: 0.65
  neutral: 0.1
