name: MafiaCraft
main: mddev0.mafiacraft.MafiaCraft
version: 1.0
api-version: 1.19
depend: [ProtocolLib]
commands:
  mafiacraftadmin:
    description: Command for Administrators to manage and start MafiaCraft games.
    aliases: [mca, mafiacrafta, mafcrafta, mafiaadmin]
  mafiacraft:
    description: Shows players of a MafiaCraft game information about their status.
    aliases: [mafiacraft, mafcraft, mafia, maf]