package mddev0.mafiacraft.abilities;

public enum Ability { // TODO: if grayed out, not implemented yet.
    PROTECTION,
    CHARISMA, // Has no class
    SUCCESSION,
    FORGERY,
    ASSASSINATION,
    REANIMATION,
    RETALIATION,
    HIGH_NOON,
    MARKSMAN,
    INVESTIGATE,
    WATCH,
    PERIPHERALS,
    CLEAR_SIGHT,
    RESCUE,
    AMBROSIA,
    INQUISITION,
    AMBUSH,
    THIS_IS_FINE,
    DODGE_ROLL,
    TARGET,
    TRACKING,
    SCATTER,
    TOADIFY,
    FOG_OF_WAR,
    VANISH,
    TRANSFORM,
    RAMPAGE,
    BITE,
    NEMESIS,
    CONVERT,
    HUNTING_NIGHT,
    NIGHT_OWL,
    STAKED,
    JUST_A_PRANK
}
